/* Generated By:JavaCC: Do not edit this line. DTDParserVisitor.java Version 5.0 */
/*
The MIT License (MIT)

Copyright (c) 2015 NuBean LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.nubean.michdtd.parser;

public interface DTDParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTKeyWords node, Object data);
  public Object visit(ASTdtd node, Object data);
  public Object visit(ASTTextDecl node, Object data);
  public Object visit(ASTincludeSect node, Object data);
  public Object visit(ASTignoreSect node, Object data);
  public Object visit(ASTDeclSep node, Object data);
  public Object visit(ASTEntityDecl node, Object data);
  public Object visit(ASTPI node, Object data);
  public Object visit(ASTComment node, Object data);
  public Object visit(ASTAttlistDecl node, Object data);
  public Object visit(ASTNotationDecl node, Object data);
  public Object visit(ASTelementdecl node, Object data);
}
/* JavaCC - OriginalChecksum=8eb57b39ab69edd2a862bd6d13dde97b (do not edit this line) */
