/* Generated By:JavaCC: Do not edit this line. DTDParserTreeConstants.java Version 5.0 */
/*
The MIT License (MIT)

Copyright (c) 2015 NuBean LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.nubean.michdtd.parser;

public interface DTDParserTreeConstants
{
  public int JJTNAME = 0;
  public int JJTKEYWORDS = 1;
  public int JJTDTD = 2;
  public int JJTTEXTDECL = 3;
  public int JJTVOID = 4;
  public int JJTINCLUDESECT = 5;
  public int JJTIGNORESECT = 6;
  public int JJTDECLSEP = 7;
  public int JJTENTITYDECL = 8;
  public int JJTPI = 9;
  public int JJTCOMMENT = 10;
  public int JJTATTLISTDECL = 11;
  public int JJTNOTATIONDECL = 12;
  public int JJTELEMENTDECL = 13;


  public String[] jjtNodeName = {
    "Name",
    "KeyWords",
    "dtd",
    "TextDecl",
    "void",
    "includeSect",
    "ignoreSect",
    "DeclSep",
    "EntityDecl",
    "PI",
    "Comment",
    "AttlistDecl",
    "NotationDecl",
    "elementdecl",
  };
}
/* JavaCC - OriginalChecksum=1d221a19ac83e7a21ccdf05607f7cf5f (do not edit this line) */
