/* Generated By:JavaCC: Do not edit this line. Java5ParserTreeConstants.java Version 5.0 */
/*
The MIT License (MIT)

Copyright (c) 2015 NuBean LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.nubean.java.parser;

public interface Java5ParserTreeConstants
{
  public int JJTJAVA = 0;
  public int JJTPACKAGE = 1;
  public int JJTIMPORT = 2;
  public int JJTVOID = 3;
  public int JJTTYPEDECL = 4;
  public int JJTFIELD = 5;
  public int JJTMETHOD = 6;
  public int JJTLOCALVARIABLE = 7;
  public int JJTANNOTATION = 8;


  public String[] jjtNodeName = {
    "Java",
    "Package",
    "Import",
    "void",
    "TypeDecl",
    "Field",
    "Method",
    "LocalVariable",
    "Annotation",
  };
}
/* JavaCC - OriginalChecksum=d5f3d28c1499c88b6a425c2b34869d65 (do not edit this line) */
