/* Generated By:JavaCC: Do not edit this line. Java5ParserVisitor.java Version 5.0 */
/*
The MIT License (MIT)

Copyright (c) 2015 NuBean LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.nubean.java.parser;

public interface Java5ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTJava node, Object data);
  public Object visit(ASTPackage node, Object data);
  public Object visit(ASTImport node, Object data);
  public Object visit(ASTTypeDecl node, Object data);
  public Object visit(ASTField node, Object data);
  public Object visit(ASTMethod node, Object data);
  public Object visit(ASTLocalVariable node, Object data);
  public Object visit(ASTAnnotation node, Object data);
}
/* JavaCC - OriginalChecksum=46c3cdaf1b4f68d36c4faa63663baac8 (do not edit this line) */
