/* Generated By:JavaCC: Do not edit this line. JavaCCParserTreeConstants.java Version 5.0 */
/*
The MIT License (MIT)

Copyright (c) 2015 NuBean LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.nubean.javacc.parser;

public interface JavaCCParserTreeConstants
{
  public int JJTJAVACC = 0;
  public int JJTOPTIONS = 1;
  public int JJTOPTIONBINDING = 2;
  public int JJTVOID = 3;
  public int JJTJAVACODEPROD = 4;
  public int JJTBNFPROD = 5;
  public int JJTREGEXPROD = 6;
  public int JJTTOKENMGRDECLS = 7;
  public int JJTTOKENKIND = 8;
  public int JJTTOKENSPEC = 9;
  public int JJTEXPANSIONCHOICES = 10;
  public int JJTEXPANSION = 11;
  public int JJTEXPANSIONUNIT = 12;
  public int JJTREGEX = 13;
  public int JJTNODEDESCRIPTOR = 14;
  public int JJTCOMPILATIONUNIT = 15;
  public int JJTJAVACOMPILATIONUNIT = 16;
  public int JJTPACKAGEDECLARATION = 17;
  public int JJTIMPORTDECLARATION = 18;
  public int JJTCLASSDECLARATION = 19;
  public int JJTINTERFACEDECLARATION = 20;
  public int JJTINTERFACEMEMBERDECLARATION = 21;
  public int JJTFIELDDECLARATION = 22;
  public int JJTVARIABLEDECLARATOR = 23;
  public int JJTVARIABLEDECLARATORID = 24;
  public int JJTVARIABLEINITIALIZER = 25;
  public int JJTMETHODDECLARATION = 26;
  public int JJTMETHODDECLARATOR = 27;
  public int JJTFORMALPARAMETERS = 28;
  public int JJTFORMALPARAMETER = 29;
  public int JJTCONSTRUCTORDECLARATION = 30;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 31;
  public int JJTINITIALIZER = 32;
  public int JJTTYPE = 33;
  public int JJTPRIMITIVETYPE = 34;
  public int JJTRESULTTYPE = 35;
  public int JJTPRIMARYPREFIX = 36;
  public int JJTPRIMARYSUFFIX = 37;
  public int JJTCHARACTERLITERAL = 38;
  public int JJTFLOATINGLITERAL = 39;
  public int JJTINTEGERLITERAL = 40;
  public int JJTBOOLEANLITERAL = 41;
  public int JJTSTRINGLITERAL = 42;
  public int JJTNULLLITERAL = 43;
  public int JJTSTATEMENT = 44;


  public String[] jjtNodeName = {
    "JavaCC",
    "Options",
    "OptionBinding",
    "void",
    "JavaCodeProd",
    "BNFProd",
    "RegExProd",
    "TokenMgrDecls",
    "TokenKind",
    "TokenSpec",
    "ExpansionChoices",
    "Expansion",
    "ExpansionUnit",
    "RegEx",
    "NodeDescriptor",
    "CompilationUnit",
    "JavaCompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "ClassDeclaration",
    "InterfaceDeclaration",
    "InterfaceMemberDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "PrimitiveType",
    "ResultType",
    "PrimaryPrefix",
    "PrimarySuffix",
    "CharacterLiteral",
    "FloatingLiteral",
    "IntegerLiteral",
    "BooleanLiteral",
    "StringLiteral",
    "NullLiteral",
    "Statement",
  };
}
/* JavaCC - OriginalChecksum=1694e9dfe9bc503d4138d722bf5d4c00 (do not edit this line) */
