/* Generated By:JJTree&JavaCC: Do not edit this line. CSSParserConstants.java */
/*
The MIT License (MIT)

Copyright (c) 2015 NuBean LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.nubean.css.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int STRING = 2;
  /** RegularExpression Id. */
  int INVALID = 3;
  /** RegularExpression Id. */
  int IDENT = 4;
  /** RegularExpression Id. */
  int HASH = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 7;
  /** RegularExpression Id. */
  int uS = 8;
  /** RegularExpression Id. */
  int h = 9;
  /** RegularExpression Id. */
  int nonascii = 10;
  /** RegularExpression Id. */
  int esc = 11;
  /** RegularExpression Id. */
  int h16 = 12;
  /** RegularExpression Id. */
  int crlf = 13;
  /** RegularExpression Id. */
  int unicode = 14;
  /** RegularExpression Id. */
  int escape = 15;
  /** RegularExpression Id. */
  int nmstart = 16;
  /** RegularExpression Id. */
  int nmchar = 17;
  /** RegularExpression Id. */
  int nl = 18;
  /** RegularExpression Id. */
  int string1 = 19;
  /** RegularExpression Id. */
  int string2 = 20;
  /** RegularExpression Id. */
  int invalid1 = 21;
  /** RegularExpression Id. */
  int invalid2 = 22;
  /** RegularExpression Id. */
  int comment = 23;
  /** RegularExpression Id. */
  int name = 24;
  /** RegularExpression Id. */
  int url = 25;
  /** RegularExpression Id. */
  int esc0 = 26;
  /** RegularExpression Id. */
  int A = 27;
  /** RegularExpression Id. */
  int C = 28;
  /** RegularExpression Id. */
  int D = 29;
  /** RegularExpression Id. */
  int E = 30;
  /** RegularExpression Id. */
  int G = 31;
  /** RegularExpression Id. */
  int H = 32;
  /** RegularExpression Id. */
  int I = 33;
  /** RegularExpression Id. */
  int K = 34;
  /** RegularExpression Id. */
  int M = 35;
  /** RegularExpression Id. */
  int N = 36;
  /** RegularExpression Id. */
  int P = 37;
  /** RegularExpression Id. */
  int R = 38;
  /** RegularExpression Id. */
  int S = 39;
  /** RegularExpression Id. */
  int T = 40;
  /** RegularExpression Id. */
  int X = 41;
  /** RegularExpression Id. */
  int Z = 42;
  /** RegularExpression Id. */
  int SEMI_COLON = 43;
  /** RegularExpression Id. */
  int RBRACE = 44;
  /** RegularExpression Id. */
  int COLON = 45;
  /** RegularExpression Id. */
  int PERIOD = 46;
  /** RegularExpression Id. */
  int ASTERISK = 47;
  /** RegularExpression Id. */
  int LSQBRKT = 48;
  /** RegularExpression Id. */
  int RSQBRKT = 49;
  /** RegularExpression Id. */
  int EQ = 50;
  /** RegularExpression Id. */
  int LPAREN = 51;
  /** RegularExpression Id. */
  int RPAREN = 52;
  /** RegularExpression Id. */
  int PAGE_SYM = 53;
  /** RegularExpression Id. */
  int IMPORT_SYM = 54;
  /** RegularExpression Id. */
  int MEDIA_SYM = 55;
  /** RegularExpression Id. */
  int CHARSET_SYM = 56;
  /** RegularExpression Id. */
  int CDO = 57;
  /** RegularExpression Id. */
  int CDC = 58;
  /** RegularExpression Id. */
  int INCLUDES = 59;
  /** RegularExpression Id. */
  int DASHMATCH = 60;
  /** RegularExpression Id. */
  int URI = 61;
  /** RegularExpression Id. */
  int FUNCTION = 62;
  /** RegularExpression Id. */
  int LBRACE = 63;
  /** RegularExpression Id. */
  int COMA = 64;
  /** RegularExpression Id. */
  int PLUS = 65;
  /** RegularExpression Id. */
  int GREATER = 66;
  /** RegularExpression Id. */
  int EMS = 67;
  /** RegularExpression Id. */
  int EXS = 68;
  /** RegularExpression Id. */
  int LENGTH = 69;
  /** RegularExpression Id. */
  int ANGLE = 70;
  /** RegularExpression Id. */
  int TIME = 71;
  /** RegularExpression Id. */
  int FREQ = 72;
  /** RegularExpression Id. */
  int DIMENSION = 73;
  /** RegularExpression Id. */
  int PERCENTAGE = 74;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<STRING>",
    "<INVALID>",
    "<IDENT>",
    "<HASH>",
    "<NUMBER>",
    "<IMPORTANT_SYM>",
    "<uS>",
    "<h>",
    "<nonascii>",
    "\"\\\\\"",
    "<h16>",
    "\"\\r\\n\"",
    "<unicode>",
    "<escape>",
    "<nmstart>",
    "<nmchar>",
    "<nl>",
    "<string1>",
    "<string2>",
    "<invalid1>",
    "<invalid2>",
    "<comment>",
    "<name>",
    "<url>",
    "<esc0>",
    "<A>",
    "<C>",
    "<D>",
    "<E>",
    "<G>",
    "<H>",
    "<I>",
    "<K>",
    "<M>",
    "<N>",
    "<P>",
    "<R>",
    "<S>",
    "<T>",
    "<X>",
    "<Z>",
    "\";\"",
    "\"}\"",
    "\":\"",
    "\".\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"@page\"",
    "\"@import\"",
    "\"@media\"",
    "\"@charset\"",
    "\"<!--\"",
    "\"-->\"",
    "\"~=\"",
    "\"|=\"",
    "<URI>",
    "<FUNCTION>",
    "<LBRACE>",
    "<COMA>",
    "<PLUS>",
    "<GREATER>",
    "<EMS>",
    "<EXS>",
    "<LENGTH>",
    "<ANGLE>",
    "<TIME>",
    "<FREQ>",
    "<DIMENSION>",
    "<PERCENTAGE>",
    "\"/\"",
    "\"-\"",
  };

}
